name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps (workspaces)
        run: npm ci --workspaces --include-workspace-root
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
